### ISSUE TITLE
Getting angles - 'get_servo_two' returns the angle of servo_1 

### ISSUE THREAD

**Issue by baychillidog** [pimoroni/pantilt-hat#10]
When getting the angle of the tilt, the angle of the pan is returned.

Line 421 of [pantilt.py](https://github.com/pimoroni/pantilt-hat/blob/master/library/pantilthat/pantilt.py) of get_servo_two is:

`us = self._i2c_read_word(self.REG_SERVO1)`

to fix this should read:

`us = self._i2c_read_word(self.REG_SERVO2)`

**Comment by Gadgetoid** [comment]
Drat! Good catch, thank you. Looks like I had a glaring gap in my test coverage!

**Comment by robmarkcole** [comment]
Can confirm this error :-)

**Comment by robmarkcole** [comment]
Any chance of a pull to fix this one? Hoping to publish https://github.com/robmarkcole/pan-tilt-phat-HASS with this functionality

**Comment by robmarkcole** [comment]
ping?

**Comment by baychillidog** [comment]
Thanks to @Gadgetoid  - was fixed straight away https://github.com/pimoroni/pantilt-hat/commit/6be6df52e84c34d7d8f6385d5084eba1f40b2f5c

**Comment by robmarkcole** [comment]
Any chance of releasing this as a new release on Pypi?
