### ISSUE TITLE
pantilthat not available for python2

### ISSUE THREAD

**Issue by ryderdonahue** [pimoroni/pantilt-hat#16]
pantilthat refuses to show up in my available modules for python2.
I have run `sudo apt-get install python-pantilthat` and I am able to verify that pantilthat is installed for python3, but no matter what I try I am unable to get it to install for python2

**Comment by Gadgetoid** [comment]
Which version of Raspbian is this? `python-pantilthat` is the Python 2 package, whereas `python3-pantilthat` is the Python 3 package.
