### ISSUE TITLE
pan() and tilt() with no delay between leaves servos stuck

### ISSUE THREAD

**Issue by bringert** [pimoroni/pantilt-hat#17]
I've found that if I call pan() and tilt() right after each other, with no delay in between, both servos seem to get stuck.

```
import pantilthat
import time

dir = 1
while True:
  try:
    pantilthat.pan(dir*90)
# Without this sleep, the servos get stuck most of the time
#    time.sleep(0.1)
    pantilthat.tilt(dir*45)
    dir *= -1
    time.sleep(2)
  except KeyboardInterrupt:
    break
```

**Comment by Gadgetoid** [comment]
I suspect this is probably a current consumption issue and not something software related.

The startup current for a servo is pretty hefty, and moving them both at the same time places the most demand on your power supply.

What type of power supply are you using, what's it rated at?
