### ISSUE TITLE
v0.0.5 error: no version_info

### ISSUE THREAD

**Issue by robmarkcole** [pimoroni/pantilt-hat#19]
As title, I get an error `version_info` is not defined

**Comment by PowerMeep** [comment]
Looking at the code, this is supposed to be "sys.version_info".
Making this change locally as well and importing sys makes this specific error go away, but this change really does need to be in the repo.

**Comment by Gadgetoid** [comment]
The facepam is strong with this one! Thanks for reporting.

I've prepped a new release, and clearly need to get some proper testing added to this repository.

See: https://github.com/pimoroni/pantilt-hat/commit/543c92852fa227fffc0768599a00e47de28a3e33
