### ISSUE TITLE
Tilt range seems incorrect

### ISSUE THREAD

**Issue by scott0123** [pimoroni/pantilt-hat#27]
The tilt angle seems to work best in the range [0, 120] for the recommended hardware.
This library defaults to [-90, 90], which may not be ideal.

Pan angles are fine as is.

**Comment by scott0123** [comment]
Update: my pan/tilt motors came incorrectly configured. The issue was not on the software side.

**Comment by Gadgetoid** [comment]
Sorry didn't catch this in time- but glad you're up and running!
