### ISSUE TITLE
python3-smbus required

### ISSUE THREAD

**Issue by sejgit** [pimoroni/pantilt-hat#6]
on raspbian, all updated/upgraded.
library works fine with hat in python2
when I try to import in python3 it kicks out with needing python3-smbus and that i should install it.
reinstalled both python3-pantilthat & python3-smbus using apt-get --reinstall  ... no joy.

thoughts?  i may try the pip3 install for kicks?

**Comment by RogueM** [comment]
when you say Raspbian fully upgraded, what exactly do you mean (what specific commands have you ran)? what does the following yield:

`python3 --version`
