### ISSUE TITLE
Documentation and edge pins

### ISSUE THREAD

**Issue by RogerHardiman** [pimoroni/pantilt-hat#8]
Hi
On the top of the Pan-Tilt HAT are some breakouts for
Power, SPI, I2C, UART, PWM and SPI.

The documentation (on GitHub) does not mention any of these pins.
The only one I wanted to check was the PWM pin.
Does that bring the "Data" line from the "LIGHT" connector to the the edge of the board or is that the unused 4th PWM Output from the PIC?

Thanks

**Comment by RogueM** [comment]
those are GPIO brought straight from the Pi, nothing to do with the PIC.

... check https://pinout.xyz for details, but essentially that means PWM corresponds to bcm18 (and it can be used for something else than PWM if you want, labels are indicative and what most people might want to use them for).
